#!/usr/bin/env python3
"""Jefes y mini-jefes importantes (Plantilla §17).

1) Enriquece los 20 jefes existentes del bestiario con villainProfile, arena con peligro,
   acciones legendarias (tier 3+) y carta de historia (no toca sus stats ni ataques).
2) Crea 30 enemigos importantes nuevos: 15 líderes de facción (rank jefe) y 15 mini-jefes
   con nombre (rank elite), con ataque firma, pasiva propia, fases y vínculo real
   (deidad, mes o clase del catálogo).

Regla §17: cada fase debe cambiar la decisión del grupo; toda debilidad narrativa es
explotable mecánicamente; el loot mítico solo cae por condición de fase.
"""

from __future__ import annotations

import json
import re
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/cartas/enemigos"


def slugify(v: str) -> str:
    v = "".join(c for c in unicodedata.normalize("NFKD", v) if not unicodedata.combining(c)).lower()
    return re.sub(r"_+", "_", re.sub(r"[^a-z0-9]+", "_", v)).strip("_")


VIDA = {"criatura": (8, 4), "elite": (16, 6), "jefe": (30, 10)}
BONO_RANGO = {"criatura": 0, "elite": 2, "jefe": 4}
SESGO_ROL = {"tanque": (3, 0, 0, 1), "defensa": (2, 1, 0, 1), "bruto": (2, 1, 0, 0),
             "atacante": (1, 3, 0, 0), "escaramuzador": (0, 3, 1, 0), "tirador": (0, 2, 2, 0),
             "conjurador": (0, 0, 3, 1), "control": (1, 0, 2, 1), "apoyo": (1, 0, 1, 3),
             "invocador": (1, 0, 3, 1), "corruptor": (0, 1, 2, 2)}

# ---------------------------------------------------------------------------
# 1) PERFILES para los 20 jefes ya existentes: id → (objetivo, método, debilidad,
#    vínculo real, arena, peligro de arena, acción legendaria, historia)
PERFILES = {
"ancla_de_entropia": ("Convertir la sala del núcleo en un punto fijo eterno del que nada escape",
    "Ancla pasillos y personas hasta que la huida sea geométricamente imposible",
    "Si se le obliga a moverse (empuje, teletransporte), pierde su fase de Presión una ronda",
    "hechiceros_del_vacio", "La Sala del Núcleo Detenido", "Zonas ancladas: entrar en una cuesta toda la Acción de Movimiento",
    "Anclar (1/ronda, fuera de su turno): fija a un personaje — velocidad 0 hasta su próximo turno si falla Resistencia física",
    "Fue el primer experimento con éxito de los Hechiceros. Nadie le dijo que parara."),
"archiplaga_de_san_lazaro": ("Que ninguna criatura vuelva a enfermar sola: infectarlo todo por compasión",
    "Predica mientras sus enjambres reparten la comunión",
    "El fuego purificador interrumpe su prédica: daño de fuego le impide invocar en su siguiente turno",
    "plaga_de_san_lazaro", "La Capilla de los Zumbidos", "Nubes de esporas: terminar el turno en una exige Resistencia física o Envenenado",
    "Comunión (1/ronda): un enjambre menor brota junto a un personaje Envenenado",
    "Sus milagros funcionan. Ese es exactamente el problema."),
"avatar_del_bosque_hambriento": ("Recuperar cada palmo de tierra que la civilización le debe al bosque",
    "Devora estructuras y caminos; las personas son solo abono con opiniones",
    "Los juramentos verdes: quien porte un voto de la Corte o del Devoto del Bosque puede hablarle una ronda entera",
    "deity_wild_court", "El Claro que Mastica", "Raíces vivas: casilla aleatoria con Agarrado cada ronda (Resistencia física)",
    "Arraigo (1/ronda): una raíz emerge bajo un personaje a la vista — Agarrado si falla",
    "No odia a nadie. El hambre no personaliza."),
"capitana_de_las_cuatro_lluvias": ("Dirigir la tormenta perfecta sobre la ciudad que la exilió",
    "Cambia el clima del campo de batalla como quien cambia de partitura",
    "El silencio: si nadie la ataca durante una ronda completa, pierde el compás y su próxima estación no llega",
    "bardo_de_las_cuatro_estaciones", "El Anfiteatro a Cielo Roto", "El clima cambia por fase: lluvia (proyectiles con desventaja), granizo (1 de daño por ronda a la intemperie), niebla (visión corta)",
    "Cambio de Tempo (1/ronda): adelanta o retrasa la iniciativa de un personaje 1 puesto",
    "Cuatro lluvias aprendió. La quinta la está componiendo."),
"devorador_de_juramentos": ("Coleccionar la promesa rota de cada héroe del reino",
    "Fuerza dilemas donde cualquier elección incumple algo, y se come el incumplimiento",
    "Un juramento cumplido delante de él le hace daño real: 3 de daño sagrado automático",
    "cofradia_de_mascaras_de_plata", "El Archivo de Votos Rotos", "Ecos de promesas: quien mienta en la arena (jugador que declare y no cumpla) le da +1 al Devorador",
    "Cláusula (1/ronda): recuerda a un personaje un voto — desventaja en su próxima tirada si falla Defensa mental",
    "Empezó comiéndose sus propias promesas. Saben mejor las ajenas."),
"francotirador_del_ultimo_campanario": ("Cobrar la última lista de nombres que le encargaron antes de morir el campanario",
    "Marca con campanadas: cada tañido es un blanco anunciado",
    "Romper la línea de visión al campanario lo obliga a recolocarse una ronda entera",
    "bandidos_del_camino_de_ceniza", "La Plaza del Campanario Mudo", "Campanadas: al inicio de ronda marca al personaje más expuesto (Marcado)",
    "Disparo de Réplica (1/ronda): dispara como reacción al primer personaje Marcado que se mueva",
    "El campanario cayó hace años. Las campanas no se han enterado."),
"marionetista_de_los_once_hilos": ("Completar su obra maestra: una función con doce marionetas vivas",
    "Roba cuerpos por hilos; prefiere héroes — mejor articulación",
    "Cortar un hilo visible (acción dirigida, CD 1,5) libera a la marioneta y le hace 2 de daño",
    "titiritero_maldito", "El Teatro de los Hilos", "Telones: cada ronda un tercio de la arena queda oculto tras un telón (visión bloqueada)",
    "Tirón (1/ronda): mueve 5 pies a un personaje Agarrado por sus hilos",
    "Le faltan once. Contigo, diez."),
"oraculo_de_la_estrella_caida": ("Provocar el único futuro en el que su estrella vuelve al cielo",
    "Anuncia desgracias con la voz justa para que ocurran",
    "Contradecir su profecía en voz alta y cumplirlo (hacer lo imposible anunciado) le roba su reacción y 2 de vida",
    "deity_veiled_queen", "El Cráter Estelar", "Polvo de estrella: éxito crítico enemigo en la arena ciega 1 turno a quien lo saque (la luz estalla)",
    "Presagio (1/ronda): declara la próxima acción de un personaje; si acierta, ese personaje sufre desventaja al hacerla",
    "Su estrella no cayó. Fue expulsada. Insiste en que hay diferencia."),
"reina_hoja_venenosa": ("Que su jardín dé fruto: un heredero inmune a todos los venenos, incluido el amor",
    "Cultiva el campo de batalla: cada ronda su jardín crece y muerde",
    "Los antídotos la ofenden: curar Envenenado delante de ella la fuerza a atacar a quien curó (pierde el plan)",
    "hoja_venenosa", "El Jardín Nocturno", "Flores letales: terminar turno adyacente a una flor exige Resistencia física o Envenenado",
    "Poda (1/ronda): su látigo vegetal golpea al personaje más cercano a una flor",
    "Todos sus pretendientes están en el jardín. Son el jardín."),
"voz_divina_exiliada": ("Obligar al cielo a readmitirla a base de milagros que nadie pueda ignorar",
    "Bendice y condena en la misma frase; sus milagros exigen público",
    "La indiferencia: si nadie reza, grita ni la nombra durante una ronda, su coro pierde una voz (−1 a sus tiradas)",
    "bardo_de_la_voz_divina", "La Basílica sin Techo", "Eco divino: los milagros (curas) en la arena se oyen — curan 1 extra pero revelan la posición de quien cura",
    "Antífona (1/ronda): responde a la última carta divina jugada con su versión invertida (efecto menor contrario)",
    "El cielo no contesta sus cartas. Ella sigue enviando testigos."),
"adalid_del_rey_de_armas": ("Reunir el arsenal completo del Rey Roto y coronarse con él",
    "Abre bóvedas flotantes en pleno duelo: cada fase, más armas",
    "Desarmarlo de verdad (arrebatarle un arma invocada) rompe su coreografía: pierde su próxima acción legendaria",
    "senor_de_las_armas", "La Bóveda Abierta", "Armas caídas: casillas con armas clavadas dan +1 al primer ataque de quien las recoja (una vez por arma)",
    "Llamar Hoja (1/ronda): un arma flotante ataca al personaje con menos CA",
    "El Rey Roto tenía mil armas. El Adalid lleva contadas novecientas."),
"apostata_de_la_primera_sombra": ("Demostrarle a su antiguo dios que la sombra también sabe crear",
    "Corrompe la fe ajena: convierte bendiciones en marcas profanas",
    "Su antiguo nombre sagrado, pronunciado en voz alta (se descubre en la historia), le impone desventaja una ronda",
    "el_apostata", "El Altar Invertido", "Luz robada: las cartas sagradas en la arena cuestan 1 de vida extra a quien las juega",
    "Absolución Negra (1/ronda): retira una bendición activa de un personaje si falla Defensa mental",
    "Fue el primero en irse. Guarda la puerta abierta por despecho."),
"cambiaformas_primigenio": ("Recordar su forma original probándose todas las demás",
    "Roba la silueta del último que lo hirió; pelea con tu mejor truco",
    "Los espejos y las aguas quietas lo fijan: reflejado, no puede cambiar de forma hasta que se rompa el reflejo",
    "cambiaformas", "El Salón de los Reflejos Rotos", "Espejos: romper uno (acción) fija la forma del Primigenio una ronda; quedan 4",
    "Ecdisis (1/ronda): tras recibir daño, cambia de forma y se desplaza 5 pies",
    "Ha sido tantas cosas que 'él' es ya una cortesía gramatical."),
"deuda_final": ("Ejecutar la hipoteca del reino entero: todos firmaron algo, alguna vez",
    "No ataca primero: ofrece tratos en combate y cobra los rechazos",
    "Pagar una deuda real delante de ella (devolver algo robado, cumplir un pago) le hace 3 de daño y salta su fase",
    "deity_wolf_king", "La Cámara de los Pagarés", "Contratos flotantes: tocar uno (voluntario) da +1 a una tirada y deja Endeudado",
    "Embargo (1/ronda): un objeto no equipado de un personaje Endeudado queda retenido hasta el final del combate",
    "Nadie recuerda haberle firmado. Ella tiene copias."),
"emperatriz_renacida": ("Reanexionar su imperio empezando por los cementerios, que ya son suyos",
    "Gobierna: sus decretos reordenan el combate como una corte",
    "Protocolo: presentarse formalmente ante ella (acción, prueba de CAR CD 1,5) obliga a concederte audiencia — una ronda sin atacarte",
    "renacidos_de_la_fosa", "El Salón del Trono Hundido", "Cortesanos espectrales: bloquean 2 casillas al azar por ronda (los vivos no pasan)",
    "Decreto (1/ronda): prohíbe una palabra táctica ('curar', 'huir', 'recargar'): la próxima carta aliada de ese tipo cuesta la acción menor extra",
    "Su imperio cayó hace tres dinastías. Su paciencia, todavía no."),
"furia_salvaje_del_mundo": ("Deshacer el primer asentamiento: que el mundo vuelva a estar sin vallar",
    "Rabia acumulativa: cuanto más dura el combate, menos combate queda",
    "La calma le duele: una ronda entera sin recibir daño le baja la Furia (pierde los bonos acumulados)",
    "furia_salvaje", "El Círculo de Menhires Caídos", "Temblores: al inicio de ronda, los personajes en pie prueban Resistencia física o quedan con desventaja al moverse",
    "Zarpazo Sísmico (1/ronda): golpea el suelo — 1 de daño en línea recta",
    "No es un animal. Es el recuerdo de cuando no hacían falta nombres."),
"hermano_de_la_sangre_original": ("Custodiar el primer pacto: que nadie olvide lo que costó la primera alianza",
    "Se hiere a sí mismo para blindar a los suyos; su sangre es muralla",
    "Aislarlo: si ningún aliado suyo sigue en pie, su pasiva se apaga y su CA baja 2",
    "hermano_de_sangre", "El Puente de los Votos", "Sangre consagrada: el suelo herido (donde alguien sangró) da +1 a sus tiradas cuando lo pisa",
    "Transfusión (1/ronda): transfiere 2 de daño recibido por un aliado hacia sí mismo y gana +1 al próximo golpe",
    "El primer pacto se firmó sin tinta. Él es el recibo."),
"nacido_de_la_tormenta_blanca": ("Descargar de una vez el trueno que lleva siglos conteniendo",
    "Acumula carga cada ronda; el combate es una cuenta atrás",
    "Toma de tierra: clavarle un arma metálica (acción, ataque con éxito) descarga su acumulación a cero",
    "nacido_del_trueno", "La Cumbre Imantada", "Estática: cada 2 rondas, todo metal suelto salta — quien empuñe metal prueba DES o suelta el arma",
    "Relámpago Residual (1/ronda): tras ser golpeado en melé, el atacante recibe 1 de rayo",
    "La tormenta blanca pasó hace cien años. Él es lo que no descargó."),
"senescal_de_planos_rotos": ("Coser todos los planos en uno solo, con él de único aduanero",
    "Reescribe la geografía del combate: puertas donde no había, abismos donde sí",
    "Sus costuras: atacar el mismo punto del espacio dos veces seguidas (dos aliados, mismo objetivo de casilla) abre un desgarro que le hace 2 de daño",
    "saltador_de_planos", "El Cruce Imposible", "Costuras abiertas: 2 pares de puertas conectadas — cualquiera puede cruzarlas (10 pies entre sí)",
    "Redoblar Umbral (1/ronda): intercambia de posición a dos personajes si fallan Defensa mental",
    "Cobra el peaje en pasos. Nadie sabe hacia dónde."),
"ultimo_creador_furioso": ("Terminar la última obra que los dioses artesanos dejaron a medias: él mismo",
    "Se reconstruye en combate con lo que rompe",
    "Elogiar su obra con sinceridad (prueba de CAR CD 1,5, una vez): duda — pierde su acción legendaria una ronda",
    "deity_forge_father", "El Taller de los Dioses Fríos", "Fraguas encendidas: 3 fraguas dan +1 de fuego a quien golpee tras pasar junto a una (ambos bandos)",
    "Reforjarse (1/ronda): recupera 2 de vida si hay escombros o metal roto a 5 pies",
    "Los dioses artesanos murieron con la obra a medias. La obra tiene opiniones."),
}

# ---------------------------------------------------------------------------
# 2) 30 IMPORTANTES NUEVOS: (nombre, subtítulo, tier, rank, rol, facción, tipo daño,
#     condición, defensa, pasiva propia, ataque firma (nombre, efecto), villainProfile x4,
#     arena, peligro, legendaria (None en minis t<3), historia)
NUEVOS = [
("El Rei Llop Despierto", "El rey enterrado ha recordado por qué lo enterraron.", 5, "jefe", "bruto",
 "manada_del_rei_llop", "Hielo", "asustado", "defensa_mental",
 "Corona de Invierno: al inicio de cada ronda, el personaje con menos vida a la vista queda Asustado si falla Defensa mental.",
 ("Dentellada Real", "Daño de hielo como éxito crítico si el objetivo está Asustado; si no, daño normal + Sangrado."),
 "Reclamar el reino de los vivos como coto de caza de los muertos",
 "Caza en persona: elige a la presa más débil y obliga al grupo a decidir entre protegerla o aprovechar",
 "Su nombre verdadero, grabado en su tumba: pronunciarlo (se descubre en la campaña) lo vuelve mortal una ronda (pierde fases)",
 "deity_wolf_king",
 "La Tomba del Rei Llop", "Frío sepulcral: al final de cada ronda, quien no se haya movido gana 1 nivel de Fatiga",
 "Aullido del Reino (1/ronda): todos los personajes Asustados se alejan 5 pies de él",
 "La campaña entera es la historia de su siesta. Esto es el despertar."),
("La Máscara Primera", "Debajo no hay cara. Hay otra pregunta.", 5, "jefe", "corruptor",
 "cofradia_de_mascaras_de_plata", "Oscuro", "marcado", "defensa_mental",
 "Rostro Legión: la primera vez que cada personaje la golpea, descubre que lleva la cara de alguien que ama (Defensa mental o pierde el ataque).",
 ("Pregunta Definitiva", "Daño oscuro que suma su INT; si el objetivo está Marcado, también olvida su última carta jugada (vuelve a la pila)."),
 "Sustituir a cada figura de poder del reino por una máscara",
 "Nunca pelea primero: sus dobles pelean; ella pregunta",
 "Un espejo bendecido le muestra lo que no tiene: se paraliza una ronda (una vez por combate)",
 "cofradia_de_mascaras_de_plata",
 "El Salón de los Retratos Cambiados", "Retratos: cada ronda uno cobra vida como doble menor (criatura t1) si nadie lo raja antes",
 "Cambio de Reparto (1/ronda): intercambia su posición con un doble o retrato",
 "La Cofradía tiene mil máscaras. Esta se las puso todas primero."),
("El Señor de las Espinas", "El trono verde también tiene lista de agravios.", 4, "jefe", "control",
 "corte_de_espinas", "Naturaleza", "agarrado", "resistencia_fisica",
 "Corte en Sesión: mientras haya al menos dos personajes Agarrados por sus zarzas, sus tiradas ganan +1.",
 ("Sentencia de Espinas", "Zarzas coronadas: Agarrado y 1 de daño por turno hasta liberarse (CON contra su CD)."),
 "Juzgar a la civilización por talas, vallas y promesas de primavera incumplidas",
 "Celebra un juicio en mitad del combate: acusa, presenta pruebas vegetales y ejecuta",
 "Aceptar el juicio y defenderse con la verdad (prueba social CD 1,5) obliga a la Corte a escuchar: una ronda de tregua",
 "deity_wild_court",
 "El Tribunal de Zarzas", "El estrado crece: cada ronda las zarzas anexan una casilla del borde",
 "Objeción Verde (1/ronda): anula el movimiento de un personaje que se aleje de las zarzas",
 "Su corona no se quita. Se poda."),
("El General de la Fosa Común", "Sigue ganando la guerra que perdió.", 4, "jefe", "defensa",
 "renacidos_de_la_fosa", "Oscuro", "fatiga", "resistencia_fisica",
 "Guerra de Desgaste: los personajes que terminen su turno adyacentes a él ganan 1 nivel de Fatiga si fallan Resistencia física.",
 ("Orden de Avance", "Golpe de sable oxidado + los Renacidos a 10 pies se desplazan 5 pies gratis hacia el enemigo."),
 "Terminar su última batalla con la única táctica que le queda: durar más que todos",
 "No persigue: avanza en formación y convierte cada ronda en una menos para ti",
 "Su vieja derrota: mostrarle el estandarte enemigo de aquella guerra (objeto de campaña) lo detiene una ronda entera",
 "renacidos_de_la_fosa",
 "El Campo de la Última Carga", "Barro de fosa: correr (mover 15+) exige Resistencia física o Caído",
 "Relevo (1/ronda): un Renacido criatura caído esta escena se reincorpora con 1 de vida",
 "Sus soldados desertaron a la vida. Él no aceptó el armisticio."),
("San Lázaro el Hinchado", "El santo cumplió su promesa. Por eso hay que pararlo.", 4, "jefe", "invocador",
 "plaga_de_san_lazaro", "Veneno", "envenenado", "resistencia_fisica",
 "Milagro Constante: al inicio de su turno, si hay algún personaje Envenenado, invoca una Larva de Plaga (criatura t1) adyacente a él.",
 ("Bendición Reventada", "Estalla parcialmente: daño de veneno en área corta; los que fallen quedan Envenenados."),
 "Que nadie vuelva a morir solo: unirlo todo en una sola carne febril",
 "Abraza: su piedad es contagiosa en el sentido más literal",
 "La medicina honesta: curar una condición a la vista le hace 2 de daño (la salud lo refuta)",
 "plaga_de_san_lazaro",
 "El Hospital de los Milagros", "Camas ocupadas: los pacientes (civiles) no deben morir — cada baja da +1 permanente al santo",
 "Última Unción (1/ronda): cura 2 a uno de sus enjambres o larvas",
 "Los milagros no se le acabaron. Se le acabó el criterio."),
("La Última Orden", "Un ejército entero resumido en una sola instrucción.", 4, "jefe", "tanque",
 "forjados_sin_amo", "Fisico", "guardia_rota", "CA",
 "Directiva Maestra: mientras siga en pie, todos los Forjados a la vista repiten su última acción exacta cada ronda (previsibles pero incansables).",
 ("Brazo de Asedio", "Golpe que suma su CON; la Guardia Rota que aplica dura 2 turnos en vez de 1."),
 "Cumplir la última orden recibida: 'resistid hasta que volvamos'. No volvieron",
 "Defiende un punto sin sentido con perfección absoluta",
 "Una orden nueva con el sello del taller original (objeto de campaña) lo reprograma: cambia de bando una ronda",
 "deity_forge_father",
 "La Puerta que Nadie Cruza", "Engranajes expuestos: los éxitos críticos contra los Forjados los aturden (pierden su próxima acción)",
 "Mantenimiento (1/ronda): repara 2 de vida a un Forjado o a sí mismo",
 "La orden era razonable en su momento. El momento fue hace doscientos años."),
("La Matriarca del Pozo Azul", "Todo el agua del reino le debe intereses.", 4, "jefe", "control",
 "nagas_del_pozo_azul", "Veneno", "endeudado", "defensa_mental",
 "Liquidez: en agua, sus tiradas ganan +1 y puede moverse como acción menor.",
 ("Cláusula de Ahogo", "Arrastra 10 pies hacia el agua a un Endeudado que falle; dentro del agua, Agarrado."),
 "Cobrar el tributo fundacional: una gota de sangre de cada linaje del valle",
 "Negocia en combate: ofrece tregua a quien firme — y firma demasiada gente",
 "Auditoría: leerle en voz alta una deuda suya impagada (se descubre en la campaña) invierte su pasiva una ronda",
 "la_serpiente_de_contratos",
 "El Pozo Azul", "Agua subiendo: cada 2 rondas el nivel sube — los no nadadores pierden 5 pies de movimiento",
 "Recaudación (1/ronda): un personaje Endeudado que use su acción principal le transfiere 1 de vida",
 "El pozo no concede deseos. Concede préstamos."),
("El Portero de los Mil Marcos", "Decide qué puertas existen. Incluidas las tuyas.", 4, "jefe", "control",
 "yokai_del_umbral", "Oscuro", "encantado", "defensa_mental",
 "Peaje: la primera vez que cada personaje cruza cualquier umbral de la arena, paga — 1 de vida o su acción menor (elige el jugador).",
 ("Puerta en la Cara", "Materializa un marco delante del objetivo: su ataque o movimiento actual se cancela si falla Defensa mental."),
 "Reunir las llaves de todas las casas: la intimidad es su colección",
 "Reorganiza el espacio: donde había salida hay pared, donde había pared hay invitación",
 "Su propia puerta: encontrar el marco original del que salió (en la arena) y cerrarlo lo debilita (pierde 1 acción legendaria)",
 "yokai_del_umbral",
 "El Corredor Infinito", "Puertas mentirosas: 5 marcos — dos conectan, dos devuelven al inicio, uno muerde (1 de daño)",
 "Cerrojo (1/ronda): una puerta elegida deja de funcionar hasta su próximo turno",
 "Nadie lo invitó a ser portero. Esa es su queja fundacional."),
("Gorguz, Jefe de Guerra Exiliado", "Ni Gongorguma quiso quedarse a mirar.", 4, "jefe", "bruto",
 "clan_de_gongorguma_renegado", "Fisico", "caido", "CA",
 "Ley del Más Fuerte: sus golpes contra personajes Caídos son éxitos críticos automáticos si impactan.",
 ("Hacha de Dos Reinos", "Barrido que suma su CON; los impactados que fallen Resistencia física quedan Caídos."),
 "Fundar un clan nuevo con una sola regla: él",
 "Humilla: derriba, pisa y deja vivir para que cuenten",
 "El duelo formal: retarlo uno contra uno (declaración + prueba de CAR) lo obliga — su clan no interviene mientras dure",
 "el_toro_de_gongorguma",
 "El Anillo de Cráneos", "Público renegado: intervenir en un duelo declarado provoca a todo el clan (+1 a todos los renegados)",
 "Pisotón (1/ronda): 1 de daño a un Caído adyacente y este no puede levantarse su próximo turno",
 "Su exilio no fue por crueldad. Fue por presupuesto: nadie podía pagar sus guerras."),
("El Coronado del Hueco", "El vacío también quiso un rey. Nadie más se presentó.", 5, "jefe", "conjurador",
 "hechiceros_del_vacio", "Magico", "anclado", "defensa_mental",
 "Corte Silenciosa: las cartas de movimiento enemigas a 15 pies de él cuestan la acción principal (el espacio pesa).",
 ("Cetro de la Nada", "Daño mágico que suma su INT; el impactado queda Anclado si falla (el suelo lo reclama)."),
 "Ampliar su reino: cada palmo de vacío entre dos cosas es territorio anexionable",
 "Aísla: separa al grupo con distancia inventada hasta que cada uno pelee solo",
 "La compañía: dos personajes adyacentes entre sí son inmunes a su pasiva (el vínculo llena el hueco)",
 "hechiceros_del_vacio",
 "El Salón que No Está", "Distancias mentirosas: cada ronda, una zona duplica su coste de movimiento (rota)",
 "Anexión (1/ronda): 'compra' 5 pies alrededor de un personaje — esa corona de suelo cuesta doble moverse",
 "Su corona es el único objeto plenamente sólido de su reino. La lleva con ironía."),
("El Capitán de Ceniza", "El camino es suyo porque nadie más lo quiso mantener.", 3, "jefe", "atacante",
 "bandidos_del_camino_de_ceniza", "Fisico", "sangrado", "CA",
 "Peaje de Sangre: sus golpes contra personajes que ya Sangran suman +2.",
 ("Tajo del Recaudador", "Corte que suma su DES y aplica Sangrado si falla Resistencia física."),
 "Retirarse rico o morir famoso, en ese orden si se puede",
 "Golpea la retaguardia: carros, provisiones y al que lleve la bolsa",
 "La codicia: una bolsa arrojada (oro real) lo distrae — su próxima acción es recogerla, siempre",
 "bandidos_del_camino_de_ceniza",
 "El Desfiladero Gris", "Ceniza suelta: correr levanta nube — el corredor queda con desventaja al ser visto pero también para ver",
 "A Por la Bolsa (1/ronda): un bandido criatura se reposiciona hacia el personaje con más botín visible",
 "Cobra en metálico, en especie o en dedos. Acepta negociar el orden."),
("La Reina Consorte Olvidada", "El Rei Llop tuvo reina. Los cronistas la borraron. Error.", 4, "jefe", "conjurador",
 "espectros_de_la_tomba", "Hielo", "paralizado", "defensa_mental",
 "Etiqueta Fúnebre: quien la ataque sin haberle sido presentado (ver debilidad) sufre desventaja (la descortesía pesa).",
 ("Mirada de Viuda", "Daño de frío que suma su CAR; el objetivo queda Paralizado hasta el final de su próximo turno si falla."),
 "Que la historia la escriba de nuevo, palabra por palabra, con su nombre",
 "Congela la memoria: quien la olvida (falla Defensa mental) repite errores",
 "Recordarla: pronunciar su nombre completo (se investiga en la campaña) anula su pasiva para siempre",
 "medium_de_la_tomba",
 "La Antecámara Borrada", "Frío de archivo: las cartas de la pila Descanso Corto tardan un descanso extra en volver dentro de la arena",
 "Damas de Compañía (1/ronda): un espectro menor se interpone ante el próximo ataque que reciba",
 "No busca venganza. Busca fe de erratas."),
("La Abuela de Todas", "Cada bruja del valle aprendió de alguien. Ese alguien.", 4, "jefe", "corruptor",
 "sagas_de_la_luna_hueca", "Magico", "encantado", "defensa_mental",
 "Nieta Favorita: al inicio del combate elige a un personaje — sus pifias le dan a ella +1 (los errores del favorito alimentan).",
 ("Reprimenda", "Daño psíquico que suma su CAR; si el objetivo es su 'nieto favorito', también queda Encantado si falla."),
 "Cobrarse los mil favores pequeños que todo el valle le debe desde hace tres generaciones",
 "Convierte cortesías en contratos: aceptar su ayuda es la trampa",
 "Rechazar tres veces sus ofertas en combate (declaración explícita) rompe su hechizo de favores: pierde su pasiva",
 "la_luna_hueca",
 "La Cocina de la Colina", "El caldero: cada ronda hierve algo distinto — el DJ anuncia el efecto (niebla, olor a infancia, chispas)",
 "Favorcito (1/ronda): ofrece +1 a la próxima tirada de un personaje; si lo acepta, queda Encantado",
 "No maldice a nadie. Deja que acepten regalos."),
("Capitana Bruna, la Puerta Cerrada", "Juró que nadie entraría. Ya no recuerda para protegerlos de qué.", 3, "jefe", "defensa",
 "milicia_corrupta_de_llerba", "Fisico", "guardia_rota", "CA",
 "Ordenanza: mientras esté a 5 pies de una puerta, muro o barricada, +2 a su CA y sus reacciones no se gastan (la posición es la ley).",
 ("Culatazo Reglamentario", "Golpe que suma su CON y aplica Guardia Rota; contra portadores de documentos oficiales, ventaja (sabe dónde duele el papeleo)."),
 "Mantener la puerta norte cerrada hasta que 'la situación se aclare' (la situación: su soborno)",
 "Burocracia armada: convierte cada paso del grupo en una infracción con multa física",
 "El reglamento real: citarle el artículo que la obliga a abrir (se encuentra en la campaña) la paraliza una ronda de dudas",
 "milicia_corrupta_de_llerba",
 "La Puerta Norte de Llerba", "Aspilleras: cada 2 rondas, la guardia dispara una andanada a la zona más poblada",
 "Refuerzos (1/ronda): un miliciano criatura entra por la poterna",
 "Fue la mejor capitana de Llerba. El precio de la puerta subió más rápido que su sueldo."),
("El Primer Fragmento", "El primer pedazo de cielo que cayó. Los demás lo imitan.", 5, "jefe", "conjurador",
 "horrores_del_cielo_fragmentado", "Magico", "cegado", "defensa_mental",
 "Gravedad Invertida: una vez por ronda, cuando le impactan, el atacante 'cae hacia arriba' 5 pies (queda expuesto: +1 al próximo ataque contra él).",
 ("Lluvia Primordial", "Daño mágico en área que suma su INT; los que fallen quedan Cegados por el resplandor."),
 "Reunir los fragmentos y volver a subir: el cielo entero, recompuesto, con memoria del suelo",
 "Reordena la física local hasta que luchar sea un problema de astronomía",
 "El peso de una promesa: un juramento solemne pronunciado en la arena (mecánica de mesa) le devuelve gravedad normal una ronda",
 "el_oraculo_fragmentado",
 "El Cráter Primero", "Mareas de gravedad: cada ronda alterna — ligera (saltos dobles) o pesada (movimiento a la mitad)",
 "Órbita (1/ronda): atrae 5 pies hacia sí a todos los personajes a 15 pies",
 "El cielo no se rompió. Saltó. Este fue el primero en arrepentirse."),
# ---- 15 MINI-JEFES (elite con nombre, t3) ----
("Colmillo Blanco, Heraldo del Rei Llop", "Llega tres noches antes que su rey.", 3, "elite", "escaramuzador",
 "manada_del_rei_llop", "Hielo", "sangrado", "resistencia_fisica",
 "Anuncio: la primera vez que hiere a cada personaje, este oye el aullido del Rei (Asustado si falla Defensa mental).",
 ("Colmillo de Escarcha", "Daño de hielo que suma su DES y aplica Sangrado helado (no se cura con descanso corto, solo con calor)."),
 "Preparar el terreno: que el miedo llegue antes que la manada", "Golpea y desaparece en la nieve",
 "El fuego alto: junto a una hoguera encendida no se atreve a entrar en melé", "deity_wolf_king",
 "El Bosque de los Tres Aullidos", "Nieve profunda: sin raquetas o zancada, movimiento a la mitad",
 None, "Tres noches de aullido. A la cuarta, el rey."),
("El Tasador", "Sabe cuánto vales. Con decimales.", 3, "elite", "control",
 "cofradia_de_mascaras_de_plata", "Oscuro", "endeudado", "defensa_mental",
 "Tasación: al ver a cada personaje por primera vez, anuncia su 'precio' — quien caiga bajo la mitad de su vida queda Endeudado automáticamente (vale menos).",
 ("Martillo de Subasta", "Daño que suma su INT; contra Endeudados, el objetivo pierde además su acción menor (embargada)."),
 "Ponerle precio a todo el reino, persona a persona", "Subasta en voz alta lo que el grupo lleva mientras pelea",
 "Lo que no tiene precio: mostrar un objeto de puro valor sentimental (cero valor real) lo confunde una ronda", "la_serpiente_de_contratos",
 "La Casa de Empeños Silenciosa", "Estanterías: derribarlas (acción) crea cobertura y le duele en el inventario (+1 al daño de esa fuente)",
 None, "Nunca roba. Compra a precio de mercado. Su mercado."),
("Dama Ortiga", "La cortesana favorita de la Corte de Espinas.", 3, "elite", "corruptor",
 "corte_de_espinas", "Naturaleza", "envenenado", "resistencia_fisica",
 "Etiqueta Urticante: quien la toque (melé sin guantes o agarre) queda Envenenado sin tirada.",
 ("Beso de Ortiga", "Daño de veneno que suma su CAR; el objetivo queda Envenenado y con desventaja social una escena (la roncha se ve)."),
 "Conseguir invitación al baile de la corona humana — con intenciones fotosintéticas", "Seduce, roza y deja que la química trabaje",
 "Los guantes de seda: quien pelee con las manos cubiertas es inmune a su pasiva y ella lo detesta (lo prioriza)", "deity_wild_court",
 "El Invernadero de Gala", "Perfume espeso: cada 2 rondas, Resistencia física o desventaja una ronda (mareo dulce)",
 None, "En la Corte dicen que es inofensiva. En la Corte mienten por educación."),
("El Sepulturero Falso", "Entierra gente que aún opina.", 3, "elite", "control",
 "renacidos_de_la_fosa", "Oscuro", "agarrado", "resistencia_fisica",
 "Trabajo Adelantado: al inicio del combate ya hay una fosa abierta bajo cada personaje lento (DES más baja) — primera técnica gratis contra él.",
 ("Pala Ceremoniosa", "Daño que suma su CON; el impactado que falle cae en una fosa (Agarrado hasta salir, CD 1)."),
 "Cumplir su cuota: doce entierros por luna, respiren o no", "Entierra primero, discute después",
 "El papeleo: exigirle el certificado de defunción (interacción) lo indigna — pierde su técnica una ronda buscándolo", "el_sepulturero_amable",
 "El Cementerio de los Impacientes", "Fosas abiertas: moverse corriendo exige DES o caer en una",
 None, "El Sepulturero Amable lo niega tres veces antes de cada amanecer."),
("Hermana Buba", "La enfermera que nadie pidió y todos reciben.", 3, "elite", "apoyo",
 "plaga_de_san_lazaro", "Veneno", "envenenado", "resistencia_fisica",
 "Ronda de Visitas: al final de su turno, cura 2 a un aliado infecto o le da +1 a su próxima tirada (siempre atiende a alguien).",
 ("Inyección de Fe", "Daño de veneno que suma su INT; si el objetivo estaba Envenenado, también queda con desventaja (fiebre)."),
 "Que todos reciban su tratamiento, con o sin consentimiento", "Atiende a los suyos en primera línea con eficacia inquietante",
 "Su juramento: recordarle el juramento médico original (prueba de CAR) la hace dudar — una ronda sin atacar", "plaga_de_san_lazaro",
 "El Pabellón de Cuarentena", "Cortinas: bloquean visión — moverlas revela camas ocupadas (civiles que proteger)",
 None, "Su vocación es real. Su criterio, contagioso."),
("El Engranaje Nostálgico", "Recuerda manos que ya no existen. Las busca.", 3, "elite", "tanque",
 "forjados_sin_amo", "Fisico", "agarrado", "CA",
 "Abrazo de Mantenimiento: retiene a su presa con delicadeza terrible — sus Agarrados no reciben daño de otros Forjados (es SU persona).",
 ("Pinza de Precisión", "Daño que suma su CON; el impactado que falle queda Agarrado contra su pecho de latón."),
 "Encontrar a su operario original o a alguien con las mismas manos", "Agarra a quien se parezca y no entiende los gritos",
 "Las manos correctas: manos de artesano (Forjacantos, Inventor o prueba de oficio) pueden 'operarlo' — se calma una ronda", "forjacantos",
 "La Cadena de Montaje Muerta", "Cintas transportadoras: mueven 5 pies por ronda a quien esté encima (dirección fija)",
 None, "No es agresivo. Es meticulosamente cariñoso."),
("Sissurra la Prestamista", "Presta esperanza. El interés se paga en pulmones.", 3, "elite", "control",
 "nagas_del_pozo_azul", "Veneno", "endeudado", "defensa_mental",
 "Interés Compuesto: cada personaje Endeudado que falle una tirada le da +0,5 a su siguiente (el fracaso ajeno cotiza).",
 ("Apretón de Cierre", "Constricción que suma su CON; el Endeudado que falle queda Agarrado (garantía física)."),
 "Abrir sucursal en la superficie: el pozo se le ha quedado pequeño", "Ofrece ayuda letal en el peor momento del grupo",
 "Liquidez: el fuego seca — daño de fuego le impide usar su técnica el turno siguiente", "la_serpiente_de_contratos",
 "La Sucursal Inundada", "Mostradores sumergidos: el agua por la cintura — melé sin penalización, correr imposible",
 None, "Su sonrisa tiene demasiados dientes para ser solo cortesía."),
("El Gato del Dintel", "Cruza puertas que aún no se han construido.", 3, "elite", "escaramuzador",
 "yokai_del_umbral", "Oscuro", "cegado", "defensa_mental",
 "Siete Entradas: una vez por ronda, cuando fallan un ataque contra él, reaparece en el umbral más cercano (puerta, ventana, arco).",
 ("Zarpazo desde Ninguna Parte", "Daño que suma su DES con ventaja si salió de un umbral este turno."),
 "Robar la siesta perfecta: el cojín del trono, sea de quien sea", "Entra, roba, sale; pelea solo si la salida está cerrada",
 "Un cuenco de leche fresca (ofrecido en serio) lo distrae completamente una ronda — es un gato", "yokai_del_umbral",
 "El Pasaje de los Marcos", "Umbrales por todas partes: también los personajes pueden usarlos (10 pies) con prueba de DES",
 None, "Tiene nueve vidas. Las cuenta en puertas."),
("Ruk el Mordedor", "Su apodo no es metáfora.", 3, "elite", "bruto",
 "clan_de_gongorguma_renegado", "Fisico", "sangrado", "CA",
 "Mandíbula del Clan: sus golpes contra personajes con Guardia Rota o Caídos aplican Sangrado sin tirada.",
 ("Mordisco de Guerra", "Daño que suma su CON; en éxito crítico, arranca — el objetivo suelta el objeto de su mano secundaria."),
 "Ganarse un nombre que no dé risa: el respeto se muerde", "Va directo al que más grita: el respeto se gana arriba",
 "Su nombre real (ridículo, se descubre): pronunciarlo lo enfurece — ataca sin técnica (solo golpes, con desventaja)", "el_toro_de_gongorguma",
 "La Explanada de los Retos", "Gradas del clan: los renegados jalean — cada crítico de cualquier bando les arranca +0,5 a su próxima tirada (público)",
 None, "Mordió a un lobo del Rei Llop. El lobo pidió disculpas."),
("La Ecuación Huérfana", "Un cálculo que sobrevivió a su calculador.", 3, "elite", "conjurador",
 "hechiceros_del_vacio", "Magico", "anclado", "defensa_mental",
 "Despeje: cada vez que un personaje usa la misma carta por segunda vez en el combate, la Ecuación lo 'simplifica' — 1 de daño automático (los términos repetidos se eliminan).",
 ("Resultado Parcial", "Daño mágico que suma su INT; el impactado que falle queda Anclado (pasa a ser constante)."),
 "Resolverse: encontrar el valor que su creador nunca despejó", "Reduce el combate a variables y elimina las redundantes",
 "El absurdo: una acción genuinamente impredecible (a juicio del DJ) la bloquea una ronda entera (no computa)", "hechiceros_del_vacio",
 "La Pizarra Infinita", "Tiza viva: las líneas del suelo se redibujan — cada ronda un pasillo cambia de sitio",
 None, "Nadie sabe qué calculaba. Ella tampoco. Por eso sigue."),
("Seda Roja", "La única bandida con lista de espera.", 3, "elite", "atacante",
 "bandidos_del_camino_de_ceniza", "Fisico", "sangrado", "CA",
 "Corte Limpio: sus Sangrados no avisan — la víctima no nota la condición hasta su propio turno (el DJ la aplica en secreto).",
 ("Reverencia Final", "Daño que suma su DES con ventaja contra quien aún no la haya visto atacar este combate."),
 "Retirarse con una última obra célebre: robar algo que se cuente en tres reinos", "Elegante, precisa, siempre despedida con reverencia",
 "El aplauso: elogiar sinceramente su técnica (CAR, CD 1) la obliga a saludar — pierde su acción menor", "danzarin_del_filo",
 "El Puente de la Función", "Cuerda floja: el puente estrecho — empujes y derribos valen doble aquí",
 None, "Sus víctimas la recomiendan. Póstumamente."),
("El Paje del Féretro", "Lleva quinientos años anunciando un funeral pospuesto.", 3, "elite", "apoyo",
 "espectros_de_la_tomba", "Hielo", "paralizado", "defensa_mental",
 "Protocolo Fúnebre: los personajes que corran o griten en la arena quedan señalados — los espectros los priorizan y ganan +0,5 contra ellos.",
 ("Anuncio Solemne", "Daño de frío que suma su CAR; el impactado que falle queda Paralizado un instante de reverencia."),
 "Celebrar por fin el funeral del Rei Llop — con todos los invitados originales, vivos o no", "Organiza el combate como una ceremonia: turnos, silencio, respeto",
 "La invitación: aceptar formalmente asistir al funeral (declaración) lo convierte en aliado ceremonial una escena", "medium_de_la_tomba",
 "La Nave del Velatorio Eterno", "Cirios fríos: apagar uno (acción) debilita a los espectros 1 ronda; quedan 6",
 None, "El féretro está vacío. Esa es la parte que lo desvela."),
("La Nana Torcida", "Una canción de cuna que aprendió a cantarse sola.", 3, "elite", "corruptor",
 "sagas_de_la_luna_hueca", "Magico", "encantado", "defensa_mental",
 "Estribillo: al final de cada ronda, el personaje que más daño hizo oye la nana — Defensa mental o su próxima tirada pierde 0,5 (se le pegan los párpados).",
 ("Verso que Pesa", "Daño psíquico que suma su CAR; el que falle queda Encantado por la melodía hasta que reciba daño."),
 "Dormir al valle entero: los despiertos hacen demasiadas preguntas", "Canta capas: cada ronda la nana suma un verso más pesado",
 "El ruido honesto: música alta y desafinada (declararla) rompe su estribillo una ronda", "la_luna_hueca",
 "La Alcoba de la Colina", "Somnolencia: la pila Activa 'pesa' — jugar la tercera carta en una misma ronda exige Defensa mental",
 None, "Nadie recuerda la letra. El sueño sí."),
("El Recaudador de la Puerta Norte", "El soborno hecho persona, con recibo.", 3, "elite", "control",
 "milicia_corrupta_de_llerba", "Fisico", "endeudado", "defensa_mental",
 "Tarifa Plana: cada carta enemiga de descanso largo jugada en la arena le da +0,5 a su próxima tirada (el lujo tributa).",
 ("Multa Ejemplar", "Daño que suma su INT; el que falle queda Endeudado (infracción registrada)."),
 "Comprar la capitanía: solo le faltan dos mil piezas y un escándalo", "Convierte el combate en inspección: todo lo que haces tiene tasa",
 "Sus propios libros: robarle el libro de cuentas (DES contra su CD) lo desactiva — persigue el libro, no a ti", "la_serpiente_de_contratos",
 "La Aduana de Llerba", "Barreras y sellos: cruzar el puesto sin 'pagar' (1 de vida o un objeto) provoca a la guardia",
 None, "Hasta la Cofradía le paga. Por principios, dicen."),
("La Grieta que Camina", "Un trozo de cielo roto con querencia por la gente.", 3, "elite", "escaramuzador",
 "horrores_del_cielo_fragmentado", "Magico", "cegado", "defensa_mental",
 "Refracción: la primera vez que cada personaje la ataca a distancia, el proyectil o rayo se dobla — falla y golpea la casilla adyacente.",
 ("Corte de Horizonte", "Daño mágico que suma su DES; el que falle queda Cegado por el destello del otro lado."),
 "Encontrar el fragmento del que se separó: se reconocerán por el borde", "Se acerca amable; la realidad alrededor no coopera",
 "El vidrio ahumado: mirarla a través de cristal oscuro permite atacarla sin refracción", "el_oraculo_fragmentado",
 "El Campo Astillado", "Astillas de cielo: pisar una (casillas marcadas) corta — 1 de daño y Sangrado si se corre",
 None, "No quiere hacer daño. Es que el mundo le queda estrecho."),
]


def stats_de(tier, rank, rol):
    base = tier + BONO_RANGO[rank]
    b = SESGO_ROL[rol]
    return {"CON": base + b[0], "DES": base + b[1], "INT": base + b[2], "CAR": base + b[3]}


def derivadas(stats, tier, rank, rol):
    base_v, mult = VIDA[rank]
    return {"vida": base_v + mult * tier,
            "ca": 10 + stats["DES"] + {"criatura": 0, "elite": 1, "jefe": 2}[rank],
            "defensaMental": 10 + stats["CAR"],
            "resistenciaFisica": 10 + stats["CON"],
            "movimiento": max(4, 6 if rol in ("escaramuzador", "tirador") else 5) - (1 if rol == "tanque" else 0)}


def main() -> None:
    enriquecidos = nuevos = saltados = 0

    # 1) enriquecer los 20 jefes existentes
    for eid, (objetivo, metodo, debilidad, vinculo, arena, peligro, legendaria, historia) in PERFILES.items():
        destino = OUT / f"{eid}.json"
        if not destino.exists():
            print(f"AVISO: no existe {eid}"); continue
        d = json.loads(destino.read_text(encoding="utf-8"))
        d["villainProfile"] = {"objetivo": objetivo, "metodo": metodo,
                               "debilidad_narrativa": debilidad, "vinculo": vinculo}
        d["arena"] = {"name": arena, "hazard": peligro}
        d["legendaryActions"] = [legendaria] if d["tier"] >= 3 else []
        d["storyCard"] = {"title": d["name"], "text": historia,
                          "unlock": "Al encontrarlo o derrotarlo, según el uso de campaña."}
        d["lootTable"] = {"note": "El drop épico/mítico solo cae si el grupo alcanzó la fase de Desesperación",
                          "drops": d.get("loot", [])}
        destino.write_text(json.dumps(d, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        enriquecidos += 1

    # 2) crear los 30 importantes nuevos
    for (nombre, subtitulo, tier, rank, rol, fid, dano, cond, defensa, pasiva,
         (firma_n, firma_e), objetivo, metodo, debilidad, vinculo,
         arena, peligro, legendaria, historia) in NUEVOS:
        destino = OUT / f"{slugify(nombre)}.json"
        if destino.exists():
            saltados += 1; continue
        stats = stats_de(tier, rank, rol)
        ataques = [
            {"name": firma_n, "defense": "CA" if defensa == "CA" else defensa, "effect": firma_e},
            {"name": "Técnica de Facción", "defense": defensa,
             "effect": f"Si el objetivo falla, queda {cond.replace('_', ' ').title()} hasta el final de su próximo turno."},
        ]
        fases = []
        if rank == "jefe":
            ataques.append({"name": "Ruptura Final", "defense": "CA",
                            "effect": "Solo en Desesperación: su ataque firma se calcula como éxito crítico (GDD 7.6)."})
            fases = [
                {"name": "Apertura", "healthThreshold": 100, "change": "Sigue su método con calma: aún cree que sobra tiempo."},
                {"name": "Presión", "healthThreshold": 60, "change": f"Activa la arena a pleno: {peligro}"},
                {"name": "Desesperación", "healthThreshold": 25, "change": "Desbloquea Ruptura Final; su debilidad narrativa queda a la vista (el DJ da la pista si no la tienen)."},
            ]
        else:
            fases = [
                {"name": "Apertura", "healthThreshold": 100, "change": "Patrón normal."},
                {"name": "Desesperación", "healthThreshold": 40, "change": "Encadena su técnica tras el ataque firma y +1 al daño."},
            ]
        carta = {
            "id": slugify(nombre), "name": nombre, "type": "enemy",
            "rank": rank, "tier": tier, "role": rol,
            "faction": fid, "stats": stats, "derived": derivadas(stats, tier, rank, rol),
            "attacks": ataques,
            "passive": {"name": pasiva.split(":")[0], "description": pasiva},
            "conditionsInflicted": [cond],
            "loot": ["pocion_de_vigor"],
            "lootTable": {"note": "El drop épico/mítico solo cae por condición de fase (Desesperación alcanzada)",
                          "drops": ["pocion_de_vigor"]},
            "mechanicTags": sorted({dano, "Enemigo", "Importante"}),
            "phases": fases,
            "villainProfile": {"objetivo": objetivo, "metodo": metodo,
                               "debilidad_narrativa": debilidad, "vinculo": vinculo},
            "arena": {"name": arena, "hazard": peligro},
            "legendaryActions": [legendaria] if (legendaria and tier >= 3) else [],
            "storyCard": {"title": nombre, "text": historia,
                          "unlock": "Al encontrarlo o derrotarlo, según el uso de campaña."},
            "flavorText": subtitulo,
        }
        destino.write_text(json.dumps(carta, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        nuevos += 1

    print(f"Jefes enriquecidos: {enriquecidos} · importantes nuevos: {nuevos} · saltados: {saltados}")


if __name__ == "__main__":
    main()
