#!/usr/bin/env python3
"""Migra los 12 meses de nacimiento al esquema canónico de Trasfondos (Prompt Maestro §4b).

Formato characterCreation: narrativo puro, sin NINGUNA mecánica. Cada lista ofrece 5
opciones (3 propias del mes + 2 de su energía) para que dos personajes del mismo mes
puedan ser completamente distintos. Ids mes_* intactos (los referencian deidades y NPCs).
El alineamiento es el arquetipo del mes (p. ej. "El Ermitaño Armónico").

REESCRIBE deliberadamente los 12 archivos: es una migración de esquema, no un lote nuevo.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data/cartas/transfondos"


def ops(prefijo, clave, items):
    """items: lista de (titulo, descripcion) → opciones con id estable."""
    campo = "title" if clave == "personality" else "name"
    out = []
    for i, (titulo, desc) in enumerate(items, 1):
        out.append({"id": f"{clave}_{prefijo}_{i}", campo: titulo, "description": desc})
    return out


# Pools por energía: 2 opciones extra por lista, compartidas entre meses hermanos.
ENERGIA = {
"Vegetación": {
    "personalities": [("Crece hacia la luz", "Busca siempre el lado que florece de cada situación."),
                      ("Raíces primero", "Antes de actuar, pregunta de dónde viene cada cosa.")],
    "virtues": [("Paciente", "Sabe que lo importante tarda estaciones, no días."),
                ("Regenerador", "Cree que casi todo lo roto puede volver a brotar.")],
    "flaws": [("Se aferra", "Le cuesta soltar lo que ya está seco."),
              ("Lento en decidir", "Delibera como crecen los árboles: demasiado despacio para las crisis.")],
    "goals": [("Replantar lo arrasado", "Devolver la vida a un lugar que vio morir."),
              ("Un jardín propio", "Un rincón del mundo que cuidar sin pedir permiso.")],
    "fears": [("La sequía", "Que llegue un mal año y no baste con esperar."),
              ("Secarse por dentro", "Dejar de sentir cómo crecen las cosas.")],
    "ideals": [("Todo lo vivo merece su estación", "Nada debe cortarse antes de florecer."),
               ("Crecer no es competir", "El bosque entero sube junto, o no es bosque.")],
    "bonds": [("El árbol que planté", "Sigue creciendo en algún lugar; a veces sueño con él."),
              ("Las semillas de casa", "Un puñado que guardo para cuando encuentre dónde.")]},
"Tierra": {
    "personalities": [("Pisa firme", "No da un paso sin saber dónde apoya el siguiente."),
                      ("Palabra de piedra", "Lo que promete, pesa. Y lo cumple.")],
    "virtues": [("Constante", "Sigue allí cuando los demás ya se marcharon."),
                ("Sereno", "Los temblores le pasan por encima sin moverlo.")],
    "flaws": [("Inflexible", "Confunde firmeza con negarse a cambiar."),
              ("Cargador de pesos ajenos", "Se echa encima lo que nadie le pidió.")],
    "goals": [("Levantar algo que dure", "Una casa, un puente, una familia: algo que quede."),
              ("Volver con las manos llenas", "Regresar al pueblo pudiendo devolver lo que le dieron.")],
    "fears": [("El derrumbe", "Ver caer lo que tanto costó levantar."),
              ("No ser necesario", "Que el mundo aprenda a sostenerse sin él.")],
    "ideals": [("Lo que se empieza se termina", "Dejar a medias es otra forma de mentir."),
               ("La tierra no olvida", "Cada deuda con el suelo se paga tarde o temprano.")],
    "bonds": [("La casa donde nací", "Sus cimientos los puso mi gente, piedra a piedra."),
              ("La herramienta heredada", "Gastada por tres generaciones de manos como las mías.")]},
"Agua": {
    "personalities": [("Fluye alrededor", "No choca con los obstáculos: los rodea."),
                      ("Profundo y callado", "Su superficie tranquila esconde corrientes.")],
    "virtues": [("Adaptable", "Toma la forma que la situación necesita."),
                ("Escucha honda", "Oye lo que la gente no se atreve a decir.")],
    "flaws": [("Escurridizo", "Cuando las cosas aprietan, encuentra cómo no estar."),
              ("Se estanca", "Sin corriente nueva, se queda dando vueltas a lo mismo.")],
    "goals": [("Llegar al mar", "Ver con mis propios ojos dónde termina toda agua."),
              ("Entender un sueño recurrente", "Lleva años volviendo; algo quiere decirme.")],
    "fears": [("La corriente ajena", "Acabar arrastrado por planes que no eligió."),
              ("El fondo", "Lo que vive debajo de las aguas quietas.")],
    "ideals": [("Nada es permanente", "Aferrarse es la única derrota segura."),
               ("El agua no juzga la orilla", "A todos moja igual: eso es justicia.")],
    "bonds": [("El río de mi infancia", "Me sabía sus vados antes que las letras."),
              ("Una promesa hecha a la orilla", "El agua fue testigo; el agua recuerda.")]},
"Rayo": {
    "personalities": [("Chispa primero", "Actúa en el instante exacto en que lo siente."),
                      ("Cielo cambiante", "Sus humores se anuncian como las tormentas: rápido.")],
    "virtues": [("Decidido", "Cuando el momento llega, no parpadea."),
                ("Despierto", "Ve las conexiones antes de que los demás vean las piezas.")],
    "flaws": [("Se descarga de golpe", "Todo su ánimo en un estallido; luego, vacío."),
              ("Impaciente", "Lo lento le parece una ofensa personal.")],
    "goals": [("Estar en el momento justo", "Una vez llegué tarde. Nunca más."),
              ("Descifrar la señal", "Algo me marcó aquella tormenta; quiero saber qué.")],
    "fears": [("El silencio del cielo", "Que un día la intuición no llegue."),
              ("Hacer daño sin querer", "El rayo no elige dónde cae. Yo debería.")],
    "ideals": [("La verdad, aunque truene", "Mejor un estallido honesto que una calma falsa."),
               ("Cada instante es único", "Lo que no se hace ahora, no se hace.")],
    "bonds": [("La cicatriz de la tormenta", "El día que el cielo me tocó y sobreviví."),
              ("Quien me enseñó a esperar", "Me enseñó que el rayo también se prepara.")]},
"Aire": {
    "personalities": [("Ligero de equipaje", "Todo lo suyo cabe en una bolsa y una decisión."),
                      ("Voz que corta", "Dice lo que piensa con el filo del viento norte.")],
    "virtues": [("Libre", "No hay jaula que le haya durado."),
                ("Directo", "Su palabra va en línea recta, como el vendaval.")],
    "flaws": [("No echa raíces", "Cuando algo empieza a atarle, sopla hacia otro lado."),
              ("Temperamental", "Pasa de brisa a galerna sin previo aviso.")],
    "goals": [("Ver el otro lado de las montañas", "Todas. Las que hagan falta."),
              ("Derribar un muro concreto", "Hay una injusticia con nombre que me espera.")],
    "fears": [("El encierro", "Cuatro paredes y una llave ajena."),
              ("Calmarse del todo", "¿Quién es el viento cuando no sopla?")],
    "ideals": [("Nadie es dueño del aire", "Lo que respiramos todos no se puede vallar."),
               ("Mejor romper que oxidarse", "Las cadenas también se pudren, pero más lento.")],
    "bonds": [("El mapa inacabado", "Cada viaje le añade una línea; morirá incompleto y feliz."),
              ("La bandada", "Los que volaron conmigo un tramo del camino.")]},
"Fuego": {
    "personalities": [("Calor de hogar", "Su presencia templa la sala; su ausencia se nota."),
                      ("Arde por dentro", "Habla bajo, pero sus convicciones queman.")],
    "virtues": [("Protector", "Entre el peligro y los suyos, siempre él."),
                ("Cálido", "Nadie pasa frío ni hambre estando cerca.")],
    "flaws": [("Consume lo que ama", "Cuida tanto que asfixia."),
              ("Rencor de brasa", "Su enfado no estalla: dura años encendido.")],
    "goals": [("Mantener el fuego de casa", "Que nunca se apague lo que mis mayores encendieron."),
              ("Encontrar qué merece arder", "Una causa a la altura de este calor.")],
    "fears": [("Apagarse", "Despertar un día sin nada que defender."),
              ("Quemar al abrazar", "Que su fuerza hiera justo a quien protege.")],
    "ideals": [("El calor se comparte", "Un fuego que no calienta a otros es solo incendio."),
               ("Defender es un deber", "Quien puede proteger y no protege, elige el frío.")],
    "bonds": [("El hogar que juré cuidar", "Sus brasas siguen esperándome."),
              ("La persona que salvé del frío", "Desde entonces, su suerte es la mía.")]},
"Energía Suprema": {
    "personalities": [("Mira desde arriba", "Ve cada escena como parte de un dibujo mayor."),
                      ("Viejo de nacimiento", "Habla como quien ya vivió esto una vez.")],
    "virtues": [("Perspectiva", "Distingue lo urgente de lo importante sin esfuerzo."),
                ("Compasión amplia", "Le duele el mundo entero, no solo su esquina.")],
    "flaws": [("Distante", "De tanto mirar el dibujo, olvida a quienes lo pintan."),
              ("Peso del destino", "Cree que todo depende de él. Todo.")],
    "goals": [("Leer el patrón completo", "Las señales apuntan a algo; quiero verlo entero."),
              ("Dejar una marca en el cielo", "Que algo mío se recuerde cuando yo no esté.")],
    "fears": [("Que no haya patrón", "Que las estrellas sean solo piedras ardiendo."),
              ("Saber demasiado", "Hay respuestas que desordenan todas las preguntas.")],
    "ideals": [("Todo está conectado", "Ningún gesto es pequeño si se mira desde arriba."),
               ("El saber obliga", "Quien ve más lejos debe avisar a los demás.")],
    "bonds": [("La noche de las tres lunas", "Nací bajo ella; me busca desde entonces."),
              ("El cuaderno de señales", "Cada presagio anotado, esperando su fecha.")]},
}

# (id, nombre, energía, alineamiento título, alineamiento desc, descripción,
#  lore{origin, culture, environment, events[2], deities[], symbols[3], traditions[2]},
#  3×personalities, 3×virtues, 3×flaws, 3×goals, 3×fears, 3×ideals, 3×bonds)
MESES = [
("mes_de_lescarcha", "Mes de la Escarcha", "Vegetación",
 "El Ermitaño Armónico", "Busca el equilibrio entre la naturaleza, el conocimiento y el crecimiento personal.",
 "Los nacidos cuando el año se cierra en silencio: introspectivos, serenos, con una conexión mística con lo que duerme bajo la nieve.",
 {"origin": "Aldeas altas donde el invierno dura medio año y las bibliotecas son graneros de palabras.",
  "culture": "Se valora el silencio bien usado: hablar poco y anotar mucho.",
  "environment": "Bosques escarchados, ermitas, senderos que solo existen en deshielo.",
  "importantEvents": ["La Gran Helada que enterró los caminos un año entero",
                       "La llegada del primer archivo itinerante a las aldeas altas"],
  "deities": ["el_caminante_gris", "deity_wild_court"],
  "symbols": ["La hoja cubierta de escarcha", "El farol apagado al alba", "El libro con cierre de hielo"],
  "traditions": ["Escribir el primer pensamiento del año en hielo, para que se derrita",
                  "No interrumpir jamás a quien mira el fuego"]},
 [("Habla poco, dice mucho", "Prefiere escuchar antes que hablar. Cada palabra tiene un propósito."),
  ("Observa antes de entrar", "Necesita entender la sala antes de pisarla."),
  ("Cálido con pocos", "Su confianza es un invernadero: pequeña, escogida y templada.")],
 [("Reflexivo", "Piensa las cosas hasta el fondo antes de moverlas."),
  ("Sereno ante la adversidad", "El desastre no le acelera el pulso: le aclara la mente."),
  ("Observador incisivo", "Ve el detalle que desmonta la mentira.")],
 [("Apático por fuera", "Su calma parece indiferencia, y a veces lo es."),
  ("Desconfiado por naturaleza", "Da por hecho que todo regalo lleva anzuelo."),
  ("Se guarda lo importante", "Cuenta las conclusiones, nunca las heridas.")],
 [("Dominar el conocimiento antiguo", "Hay saberes enterrados que alguien debe despertar con cuidado."),
  ("Encontrar la ermita perfecta", "Un lugar tan silencioso que se oigan las ideas."),
  ("Terminar el tratado inacabado", "Mi maestro murió a mitad de frase. Yo sé cuál era.")],
 [("El deshielo de sus secretos", "Que lo que guarda salga a la luz antes de tiempo."),
  ("Las multitudes", "Demasiadas voces: ninguna se puede escuchar de verdad."),
  ("Olvidar lo aprendido", "Su memoria es su casa; teme las goteras.")],
 [("El conocimiento nunca debe destruirse", "Quemar un libro es matar a todos sus futuros lectores."),
  ("La calma es una forma de coraje", "Cualquiera grita; pocos permanecen."),
  ("Entender antes que juzgar", "Todo monstruo tiene un diario que nadie leyó.")],
 [("Mi antiguo maestro", "Me enseñó a leer el mundo dos veces antes de opinar."),
  ("La cabaña del paso alto", "Allí pasé el invierno que me cambió."),
  ("El diario cifrado", "Aún no sé quién lo escribió. Sé que me esperaba.")]),

("mes_de_la_siembra", "Mes de la Siembra", "Tierra",
 "El Custodio del Surco", "Enfocado en crear, estabilizar y regenerar; fiel a sus raíces y a sus pactos.",
 "Los nacidos cuando se abre la tierra: pacientes, protectores, incapaces de abandonar lo que empezaron a cuidar.",
 {"origin": "Comunidades agrícolas del valle, donde cada familia tiene surco y palabra.",
  "culture": "El pacto vale más que el contrato; la cosecha se comparte antes de contarse.",
  "environment": "Campos abiertos, acequias, silos comunales y ferias de semillas.",
  "importantEvents": ["El Año sin Siembra, cuando la guerra pisó los campos",
                       "La fundación del banco de semillas del valle"],
  "deities": ["la_espiga_dorada", "la_madre_de_los_doce"],
  "symbols": ["La semilla en la palma", "El arado pequeño", "El nudo de espigas"],
  "traditions": ["Plantar algo el día del nacimiento de cada hijo",
                  "Sellar los tratos con tierra en la mano, no con tinta"]},
 [("Manos que no paran", "Si hay algo que hacer, ya lo está haciendo."),
  ("Primero los suyos", "Su gente come antes que él. Siempre ha sido así."),
  ("Optimista terco", "Cree en la próxima cosecha incluso contando las pérdidas de esta.")],
 [("Paciente como el arado", "Sabe esperar lo que tarda en crecer lo bueno."),
  ("Protector de la comunidad", "Un pueblo es un cuerpo: si duele una casa, duelen todas."),
  ("Perseverante", "Vuelve a sembrar. Siempre vuelve a sembrar.")],
 [("Testarudo incansable", "Cambiar de idea le cuesta más que arar en piedra."),
  ("Cerrado a lo nuevo", "Lo que no hicieron sus abuelos le parece una moda."),
  ("No sabe descansar", "El barbecho es para los campos, cree; no para él.")],
 [("Hacer crecer un pueblo desde la semilla", "Un lugar nuevo donde nadie pase el invierno solo."),
  ("Recuperar la tierra de la familia", "Nos la quitaron con papeles. Volveré con razones."),
  ("Que nadie más pase el Año sin Siembra", "Un granero lleno para el pueblo, pase lo que pase.")],
 [("La plaga", "Lo que pudre desde dentro, sin ruido, hasta que es tarde."),
  ("Romper un pacto", "Su palabra es su apellido; perderla sería quedarse huérfano."),
  ("Irse sin dejar nada plantado", "Una vida sin cosecha a la vista.")],
 [("Se cosecha lo que se siembra", "En campos y en personas: no hay atajos."),
  ("La tierra es de quien la cuida", "Los títulos se escriben; los surcos se ganan."),
  ("Toda vida merece su riego", "Nadie crece sin que alguien lo haya regado antes.")],
 [("El pueblo natal", "Cada piedra sabe mi nombre y yo el de cada puerta."),
  ("La azada de mi madre", "Gastada justo donde ella la agarraba."),
  ("El vecino que me lo enseñó todo", "Sin ser familia, fue familia.")]),

("mes_de_laigua", "Mes del Agua", "Agua",
 "El Guardián de las Aguas Profundas", "Reflexión y saber que fluye: no impone, transforma con tiempo y palabra.",
 "Los nacidos con las lluvias largas: soñadores lúcidos, flexibles, con memoria de cauce.",
 {"origin": "Pueblos ribereños y barrios de canal, donde todo llega y todo se va flotando.",
  "culture": "Se aprende nadando y se discute remando; la prisa es de secano.",
  "environment": "Ríos lentos, molinos, embarcaderos con historias y niebla madrugadora.",
  "importantEvents": ["La Crecida que movió el pueblo entero cien pasos",
                       "El año que el río bajó rojo y nadie supo por qué"],
  "deities": ["la_senora_de_las_mareas", "la_luna_hueca"],
  "symbols": ["La gota que horada", "El remo cruzado", "La caracola de agua dulce"],
  "traditions": ["Confiar los secretos al río, en voz baja, una vez al año",
                  "No zarpar jamás sin devolver algo a la orilla"]},
 [("Sueña despierto con método", "Sus fantasías tienen planos y desembocadura."),
  ("Se adapta al interlocutor", "Habla el idioma de quien tiene delante, sin fingir."),
  ("Marea tranquila", "Nunca parece tener prisa; siempre llega.")],
 [("Flexible como la corriente", "Cambia de plan sin cambiar de destino."),
  ("Introspectivo y sabio", "Conoce sus fondos: por eso no le asustan los ajenos."),
  ("Creativo inagotable", "Donde otros ven un muro, él ya está buscando la filtración.")],
 [("Desconexión emocional", "A veces observa su propia vida desde la orilla."),
  ("Evita la confrontación", "Rodea los conflictos hasta que crecen demasiado para rodearlos."),
  ("Promete mareas", "Se compromete con la facilidad de quien fluye... y luego fluye.")],
 [("Comprender el paso del tiempo y los sueños", "Los sueños insisten; quiero saber qué cobran."),
  ("Cartografiar el río entero", "De la primera gota al mar, con todos sus nombres."),
  ("Encontrar a quien se llevó la corriente", "Alguien que quiero se fue aguas abajo. Iré aguas abajo.")],
 [("Enfrentarse a la realidad en seco", "Sin metáforas, sin rodeos: eso le aterra."),
  ("Las aguas quietas propias", "Estancarse y llamarlo paz."),
  ("Ahogarse en lo hondo de otro", "Meterse tanto en alguien que no encuentre la salida.")],
 [("Todo fluye y eso es bueno", "Las penas también son agua: pasan."),
  ("La palabra amable erosiona montañas", "La violencia rompe; la constancia moldea."),
  ("Cada uno tiene su cauce", "Forzar el curso de otro es envenenarle el agua.")],
 [("El río de casa", "Su rumor es lo primero que recuerdo."),
  ("La barca de mi abuelo", "Sigue a flote. Como su nombre."),
  ("Un sueño recurrente", "La misma puerta bajo el agua, cada luna llena.")]),

("mes_de_loracle", "Mes del Oráculo", "Rayo",
 "El Profeta del Trueno", "Lucha con voz de verdad: sueña para transformar y sacude cimientos con ideas y acción.",
 "Los nacidos bajo el Cielo Fragmentado: visionarios eléctricos, valientes ante lo desconocido, difíciles de sujetar.",
 {"origin": "Colinas del este, donde el cielo roto deja caer presagios con la lluvia.",
  "culture": "Se respeta a quien tuvo una visión... y se le vigila de cerca.",
  "environment": "Mesetas de tormenta, círculos de piedras que zumban, atalayas de vigía.",
  "importantEvents": ["La noche en que el Cielo se fragmentó sobre las colinas",
                       "La Profecía de las Tres Puertas, aún a medio cumplir"],
  "deities": ["el_oraculo_fragmentado", "la_madre_de_los_doce"],
  "symbols": ["El rayo bifurcado", "El ojo entre nubes", "La campana rajada que aún suena"],
  "traditions": ["Anotar los sueños al despertar, antes de hablar con nadie",
                  "Subir a la atalaya en cada tormenta para 'escuchar el correo'"]},
 [("Anuncia lo que ve", "Incapaz de callarse una verdad, caiga quien caiga."),
  ("Vive en dos tiempos", "Media atención aquí; la otra media, en lo que viene."),
  ("Teatral sin querer", "Hasta sus buenos días suenan a proclama.")],
 [("Inspirado por visiones", "Sus corazonadas tienen mejor puntería que muchos planes."),
  ("Valeroso ante lo desconocido", "Lo que no entiende le atrae en vez de frenarle."),
  ("Tacto profético", "Sabe decir la mala noticia del modo que salva.")],
 [("Inestable", "Su ánimo cambia con la presión atmosférica."),
  ("Pierde los objetivos largos", "Cada visión nueva le desordena la lista."),
  ("Cree que todo es señal", "A veces un cuervo es solo un cuervo. Él nunca lo acepta.")],
 [("Traducir las profecías del Cielo Fragmentado", "Alguien tiene que ordenar ese correo celeste."),
  ("Evitar UNA profecía concreta", "La vi. Es evitable. Lo demás puede esperar."),
  ("Formar a otro vidente", "Que lo que sé no muera conmigo.")],
 [("Que la visión llegue tarde", "Ver el desastre con la ceniza ya caliente."),
  ("Ser creído a medias", "Peor que el descrédito: la duda educada."),
  ("La última profecía", "Dicen que todo vidente ve su propio final. Aún no. Aún no.")],
 [("La verdad se debe decir", "Un presagio callado es una traición al futuro."),
  ("El futuro se negocia", "Nada está escrito con tinta que no se pueda discutir."),
  ("El don obliga", "Ver más es deber más.")],
 [("El círculo de piedras", "Allí oí mi primer trueno con palabras."),
  ("Mi hermana escéptica", "No cree ni una de mis visiones. Es mi ancla y lo sabe."),
  ("La profecía a medio cumplir", "Tres puertas. Ya se abrieron dos.")]),

("mes_del_sol", "Mes del Sol", "Vegetación",
 "El Corazón de las Hojas", "Late con la naturaleza y brilla entre las sombras: hace florecer lo que toca, quema si no se controla.",
 "Los nacidos en pleno esplendor: radiantes, protectores de la vida, incapaces de pasar desapercibidos.",
 {"origin": "Vegas soleadas y pueblos de fiesta larga, donde el verano se toma en serio.",
  "culture": "La alegría es un oficio respetable; la belleza, un servicio público.",
  "environment": "Campos en flor, plazas con música, colmenas y huertos desbordados.",
  "importantEvents": ["El Verano Doble, cuando no llegó el otoño",
                       "La fundación de la Fiesta de las Primeras Flores"],
  "deities": ["el_leon_del_alba", "deity_wild_court"],
  "symbols": ["El girasol", "La abeja dorada", "La corona de flores frescas"],
  "traditions": ["Regalar lo primero que florezca de cada huerto",
                  "Bailar al amanecer del primer día cálido, esté quien esté mirando"]},
 [("Entra iluminando", "Las salas se enteran de que ha llegado."),
  ("Cuida en voz alta", "Pregunta, abraza, alimenta: su cariño no sabe ser discreto."),
  ("Brilla bajo presión", "Cuanto peor pinta todo, más ancha su sonrisa. Es su escudo.")],
 [("Carismático radiante", "Cae bien hasta cuando cobra deudas."),
  ("Protector de la vida", "No pisa una flor si puede rodearla; no abandona a nadie."),
  ("Inspirador natural", "La gente hace cosas grandes solo por no decepcionarle.")],
 [("Vanidoso", "Necesita el aplauso más de lo que confiesa."),
  ("Sobreprotector", "Asfixia a quien ama con su propia sombra dorada."),
  ("No soporta la penumbra", "Los silencios largos y los cuartos cerrados le apagan.")],
 [("Esparcir la belleza de la vida", "Que cada sitio por el que pase quede más vivo."),
  ("Un festival propio", "Una fiesta que lleve mi nombre y sobreviva a mi nombre."),
  ("Hacer florecer el páramo", "Ese sitio gris del mapa: reto aceptado.")],
 [("Marchitarse", "Envejecer sin haber florecido del todo."),
  ("La sombra propia", "Lo que soy cuando nadie mira ni aplaude."),
  ("Quemar lo que quiero", "Tanto sol, sin control, agosta.")],
 [("La alegría es resistencia", "Reír en tiempos oscuros es negarle la victoria a la sombra."),
  ("La belleza es de todos", "Acaparar lo hermoso debería ser delito."),
  ("Nadie florece solo", "Todo jardín es un trabajo en compañía.")],
 [("La plaza de mi pueblo", "Aprendí a bailar antes que a discutir."),
  ("El huerto de la abuela", "Sus tomates aún no tienen rival. Ni su consejo."),
  ("Mi público primero", "Los tres vecinos que aplaudieron mi primer truco.")]),

("mes_de_la_cosecha", "Mes de la Cosecha", "Tierra",
 "El Cultivador de Equilibrios", "Persona de cimientos sólidos: puente entre el bosque y el mercado, entre el pueblo y la corona.",
 "Los nacidos cuando se recoge: trabajadores incansables, confiables, generosos con lo suyo y exigentes con lo justo.",
 {"origin": "Villas de mercado donde el campo y la ciudad se dan la mano (y se la miden).",
  "culture": "Contar bien es tan sagrado como sembrar bien; la balanza es un altar.",
  "environment": "Graneros, básculas, caminos de carro y ferias de cierre de año.",
  "importantEvents": ["La Cosecha Partida, que se repartió con el pueblo vecino en su peor año",
                       "El Pleito de las Balanzas, que dio al pueblo su fuero propio"],
  "deities": ["la_espiga_dorada", "el_hermano_mendigo"],
  "symbols": ["La balanza equilibrada", "La gavilla atada", "La llave del granero"],
  "traditions": ["El primer pan de la cosecha se hornea para desconocidos",
                  "Revisar las cuentas del año en voz alta, ante todos"]},
 [("Cuenta y reparte", "Su primera pregunta: ¿alcanza para todos?"),
  ("Firme en la feria", "Negocia sin engañar y sin dejarse."),
  ("Puente entre bandos", "Le buscan cuando el pueblo y el castillo no se hablan.")],
 [("Trabajador incansable", "El último en soltar la herramienta."),
  ("Confiable y leal", "Puedes construir encima de su palabra."),
  ("Generoso", "Da tiempo y pan sin apuntarlo en ningún libro.")],
 [("Rígido con sus convicciones", "Su balanza moral no admite pulgares."),
  ("Obsesionado con el orden", "Un almacén desordenado le duele físicamente."),
  ("Justiciero de mostrador", "Convierte cada pequeño fraude en cruzada.")],
 [("Cuidar los campos que alimentarán un reino", "Que nadie con corona olvide de dónde sale el pan."),
  ("Un fuero justo para mi villa", "Leyes que pesen igual para el carro y la carroza."),
  ("Saldar la deuda de mi casa", "Mi padre debía; yo devuelvo. Con intereses de honra.")],
 [("La balanza trucada", "Que el mundo funcione así y no se pueda arreglar."),
  ("El granero vacío en invierno", "Lo vio una vez de niño. Una fue bastante."),
  ("Convertirse en lo que combate", "Tanto medir, tanto contar... ¿y si me vuelvo avaro?")],
 [("Lo justo es sagrado", "El equilibrio no es un ideal: es el único suelo firme."),
  ("El trabajo dignifica a quien lo paga bien", "Explotar es robar con calendario."),
  ("Compartir multiplica", "La cosecha partida de mi pueblo lo demostró.")],
 [("La balanza de la familia", "Tres generaciones pesando justo."),
  ("El pueblo vecino", "Nos dieron grano en el año malo. Eso no caduca."),
  ("El libro de cuentas del bisabuelo", "Ni una tachadura en cuarenta años.")]),

("mes_del_ferro", "Mes del Hierro", "Aire",
 "La Llama del Orden Impuesto", "Voluntad encarnada: no busca la paz, sino el equilibrio a través del conflicto.",
 "Los nacidos al rojo: valientes, leales hasta la muerte, resolutivos cuando todo tiembla.",
 {"origin": "Ciudades-fragua y pasos de montaña donde la ley llegó a martillazos.",
  "culture": "El honor se mide en lo que aguantas y en a quién no abandonaste.",
  "environment": "Herrerías, cuarteles, murallas a medio reparar, banderas gastadas.",
  "importantEvents": ["El Asedio de los Cien Días que la villa resistió",
                       "El Juramento del Yunque, que fundó la guardia libre"],
  "deities": ["la_forja_del_trueno", "deity_forge_father"],
  "symbols": ["El martillo alzado", "El eslabón abierto", "La bandera remendada"],
  "traditions": ["Forjar un clavo el día de la mayoría de edad y clavarlo en la puerta común",
                  "Jurar los cargos ante el yunque, no ante el altar"]},
 [("Da un paso al frente", "Cuando preguntan quién, ya ha levantado la mano."),
  ("Habla como martilla", "Claro, seguido y sin adornos."),
  ("Duro por fuera, leal por dentro", "Su cariño parece instrucción militar. Es cariño.")],
 [("Valiente sin teatro", "El combate no le gusta: le encuentra."),
  ("Leal hasta la muerte", "Sus amistades tienen cláusula de eternidad."),
  ("Resolutivo bajo presión", "El caos le ordena las ideas.")],
 [("Temperamento explosivo", "Su paciencia es corta y su mecha, pública."),
  ("No perdona fácil", "Guarda las ofensas en frío, como el acero."),
  ("Todo es un frente", "Le cuesta entender que no toda mesa es un consejo de guerra.")],
 [("Derrocar una injusticia arraigada", "Hay un abuso con siglos de óxido. Traigo lima."),
  ("Refundar la guardia de mi villa", "Que proteger vuelva a ser un honor, no un peaje."),
  ("Devolver el golpe pendiente", "No por venganza: por equilibrio.")],
 [("Oxidarse", "Quedarse quieto mientras el mundo se tuerce."),
  ("Fallar a quien juró proteger", "Su única derrota inaceptable."),
  ("Convertir la causa en excusa", "Tanto martillo... ¿y si un día golpeo por golpear?")],
 [("La fuerza debe proteger, no dominar", "Un brazo fuerte al servicio propio es solo otra amenaza."),
  ("El orden se gana con el ejemplo", "Nadie sigue a quien no marcha delante."),
  ("Las cadenas se rompen desde dentro", "La libertad regalada dura poco.")],
 [("Mi escuadra vieja", "Los que aguantaron los Cien Días conmigo."),
  ("El martillo del maestro armero", "Me lo dio al jurar. Pesa exactamente lo que promete."),
  ("La puerta llena de clavos", "Cada clavo, un vecino hecho adulto. El mío está torcido.")]),

("mes_de_lagonia", "Mes de la Agonía", "Vegetación",
 "El Portador de la Sombra Dulce", "Alma cargada que conoce la belleza del sacrificio; abre caminos donde nadie se atreve a mirar.",
 "Los nacidos en la caída de la hoja: profundos, persistentes en el dolor, capaces de acompañar cualquier pena.",
 {"origin": "Pueblos de duelo largo, donde los funerales duran lo que haga falta.",
  "culture": "Nombrar el dolor es curarlo a medias; el arte triste es medicina.",
  "environment": "Alamedas en otoño perpetuo, talleres de luthier, cementerios con bancos.",
  "importantEvents": ["La Peste Blanca que enseñó al pueblo a despedirse bien",
                       "El Concurso de Elegías, que se celebra desde entonces"],
  "deities": ["el_sepulturero_amable", "la_madre_de_los_doce"],
  "symbols": ["La hoja a medio caer", "La cuerda de laúd rota y anudada", "La vela que gotea"],
  "traditions": ["Componer una canción para cada difunto, aunque sea de dos versos",
                  "Guardar un asiento vacío en cada celebración"]},
 [("Acompaña en silencio", "Sabe estar en la habitación difícil sin llenar el aire."),
  ("Belleza en lo roto", "Colecciona grietas: en jarras, canciones y personas."),
  ("Ríe bajito", "Su humor existe, es fino y llega cuando más falta hace.")],
 [("Persistente en el dolor", "Sigue adelante con la herida a cuestas, sin soltarla ni rendirse."),
  ("Profundo", "No tiene conversaciones pequeñas: pregunta de verdad."),
  ("Comprende el sufrimiento ajeno", "Reconoce una pena a tres mesas de distancia.")],
 [("Envidia silenciosa", "Los caminos fáciles de otros le escuecen."),
  ("Melancolía pegajosa", "A veces se instala en su pena como en un sillón."),
  ("Romantiza la herida", "Confunde sanar con traicionar el recuerdo.")],
 [("Crear la obra que inmortalice mi dolor", "Que esta pena sirva al menos de refugio a otros."),
  ("Despedirme como es debido", "Hay un funeral que me perdí. Iré, aunque sea tarde."),
  ("Aprender la canción de mi casa", "Mi madre la tarareaba. Nadie recuerda el final.")],
 [("Olvidar el rostro amado", "Que el tiempo borre lo único que le queda."),
  ("Sanar del todo", "¿Quién sería sin este peso que le da forma?"),
  ("La pena sin testigos", "Morir de tristeza en un lugar donde nadie componga nada.")],
 [("El dolor compartido pesa la mitad", "Toda pena guardada a solas se pudre."),
  ("Lo roto también es hermoso", "Las cicatrices son el arte involuntario de vivir."),
  ("Nadie se va del todo", "Mientras alguien cante su canción.")],
 [("El laúd de cuerda anudada", "Se rompió el día que ella murió. Lo anudé. Suena distinto y mejor."),
  ("El banco del cementerio", "Allí he tenido mis mejores conversaciones. Algunas, con vivos."),
  ("La elegía inacabada", "Dos versos me faltan. Llevo años.")]),

("mes_de_la_terra", "Mes de la Tierra", "Fuego",
 "El Corazón de la Tierra Silenciosa", "La esencia de lo que sostiene todo sin reclamar protagonismo; memoria viva del mundo.",
 "Los nacidos del suelo firme: arraigados, pacientes, rápidos para defender y lentos para atacar.",
 {"origin": "Fronteras duras y colonias jóvenes, donde la tierra se gana cada día.",
  "culture": "Primero el refugio, luego el muro, luego la mesa larga para todos.",
  "environment": "Territorio hostil domesticado a paciencia: empalizadas, pozos, primeros huertos.",
  "importantEvents": ["La Primera Empalizada, levantada en una sola noche entre todos",
                       "El Invierno de las Puertas Abiertas, cuando nadie durmió fuera"],
  "deities": ["el_toro_de_gongorguma", "la_espiga_dorada"],
  "symbols": ["La piedra angular", "El pozo compartido", "La mesa larga"],
  "traditions": ["Poner la primera piedra de toda casa entre todos los vecinos",
                  "Quien llega de fuera come primero y explica después"]},
 [("Sostiene sin ruido", "Es la razón de que todo funcione y nadie lo nota. Le vale."),
  ("Lento para la ofensa", "Insultarle es como insultar a una montaña: hay que insistir."),
  ("Memoria del grupo", "Recuerda quién ayudó, quién faltó y quién lo intentó.")],
 [("Conexión profunda con la naturaleza", "El terreno le habla: sabe dónde cavar y dónde no."),
  ("Arraigado y paciente", "Sus raíces aguantan las tormentas que arrancan a otros."),
  ("Protector de los débiles", "Su fuerza tiene una sola dirección: delante de los frágiles.")],
 [("Rígido ante el cambio", "Mover una costumbre le cuesta más que mover un peñasco."),
  ("No perdona la traición", "Puedes fallarle mil veces; venderle, solo una."),
  ("Silencioso de más", "Calla tanto sosteniendo que nadie sabe cuándo se está hundiendo.")],
 [("Hacer crecer una comunidad en territorio hostil", "Donde dicen que no se puede vivir: allí."),
  ("Terminar la muralla", "La empezó mi generación. La acabará."),
  ("Encontrar agua en el páramo", "Hay un pozo esperándome en algún punto del mapa.")],
 [("La traición de los de dentro", "Los muros protegen de fuera. De dentro, nada."),
  ("Ver partir a los jóvenes", "Un pueblo sin relevo es un cementerio con huerto."),
  ("Que la tierra diga no", "Haber elegido un suelo que no quiere a nadie.")],
 [("La tierra es memoria", "Cada palmo cultivado recuerda a quien lo trabajó."),
  ("Defender es el primer oficio", "Todo lo demás se aprende después de estar a salvo."),
  ("La casa se construye entre todos", "Una piedra puesta a solas es solo una piedra.")],
 [("La piedra angular de casa", "La pusimos veinte manos. Reconozco las mías."),
  ("El pozo del pueblo", "Lo cavó mi padre hasta el agua. Yo lo mantengo hasta hoy."),
  ("La frontera misma", "Esa línea dura del mapa es mi biografía.")]),

("mes_dels_aullits", "Mes de los Aullidos", "Tierra",
 "El Soñador de las Sombras", "Lleva los gritos de los que se fueron y la semilla de lo que no ha nacido: todo fin es un comienzo.",
 "Los nacidos en las noches largas: introspectivos, fieles a sus intuiciones, valientes ante la muerte.",
 {"origin": "Aldeas junto a campos santos y pasos de montaña donde el viento aúlla nombres.",
  "culture": "A los muertos se les habla con normalidad; a la muerte, con respeto y sin miedo.",
  "environment": "Nieblas bajas, cipreses, linternas votivas, senderos de peregrinación nocturna.",
  "importantEvents": ["La Noche de los Mil Aullidos, cuando el paso se cerró solo",
                       "La fundación de la Vigilia, la orden que acompaña moribundos"],
  "deities": ["deity_wolf_king", "el_sepulturero_amable"],
  "symbols": ["La linterna votiva", "El ciprés joven", "La huella de lobo en la escarcha"],
  "traditions": ["Dejar una luz encendida en la ventana las noches de viento",
                  "Contar los nombres de los idos en el solsticio, todos, sin saltarse uno"]},
 [("Cómodo en la penumbra", "Las conversaciones importantes le salen mejor de noche."),
  ("Escucha a los ausentes", "Habla de los muertos en presente, con naturalidad."),
  ("Sereno ante lo inevitable", "No negocia con lo ineludible: lo acompaña.")],
 [("Introspección profunda", "Conoce sus propias sombras por su nombre de pila."),
  ("Fiel a sus intuiciones", "Cuando su instinto aúlla, obedece."),
  ("Coraje ante la muerte", "La ha mirado tantas veces que ya se saludan.")],
 [("Aislamiento", "Se refugia en sí mismo justo cuando más manos necesita."),
  ("Idealiza el pasado", "Sus muertos eran perfectos; sus vivos, nunca lo bastante."),
  ("Nocturno hasta el error", "Vive a deshoras y se pierde lo que pasa a plena luz.")],
 [("Acompañar almas perdidas hasta el reposo", "Nadie debería cruzar solo. Nadie."),
  ("Cerrar la lista del solsticio", "Hay un nombre que nadie recuerda entero. Lo encontraré."),
  ("Hacer las paces con un fantasma propio", "Tenemos una conversación pendiente.")],
 [("Un adiós sin decir", "Las despedidas robadas no cicatrizan."),
  ("Que los aullidos callen", "El silencio total de la noche: eso sí sería mal presagio."),
  ("Cruzar sin guía", "Morir lejos, sin nadie que sepa los ritos.")],
 [("Todo fin es un comienzo", "La semilla también es un funeral de la flor."),
  ("A los muertos, la verdad", "Se les debe memoria exacta, no leyenda cómoda."),
  ("La noche también es casa", "Lo oscuro no es lo malo: es lo no mirado.")],
 [("La linterna de la ventana", "La encendía mi madre. Ahora la enciendo yo."),
  ("El ciprés que planté", "Uno por cada adiós importante. Van cuatro."),
  ("La Vigilia", "Me acogieron una mala noche. Les debo todas las buenas.")]),

("mes_de_les_ombres", "Mes de las Sombras", "Rayo",
 "La Llama de la Tempestad Interior", "Fuego que arde desde dentro: un alma marcada por el conflicto con poder para cambiar el orden.",
 "Los nacidos en la frontera de la luz: perspicaces, adaptables, valientes ante su propia oscuridad.",
 {"origin": "Callejones de ciudad vieja y barrios que la historia oficial prefiere no contar.",
  "culture": "Sobrevivir con estilo es la única etiqueta; las cadenas se estudian para romperse.",
  "environment": "Faroles rojos, tejados comunicados, tabernas con dos salidas y media.",
  "importantEvents": ["El Toque de Queda de los Tres Años, y cómo se burló cada noche",
                       "La Noche de los Faroles, cuando el barrio se defendió solo"],
  "deities": ["la_dama_del_farol_rojo", "deity_veiled_queen"],
  "symbols": ["El farol rojo", "La llave maestra", "La cicatriz con historia"],
  "traditions": ["No preguntar el nombre de nacimiento: vale el elegido",
                  "Pagar la primera ronda a quien acaba de llegar huyendo de algo"]},
 [("Lee la sala en un vistazo", "Salidas, manos y mentiras: en ese orden."),
  ("Encanto de doble filo", "Sonríe como quien negocia y negocia como quien sonríe."),
  ("Frontera andante", "Ni de la luz ni de la sombra: del borde, y orgulloso.")],
 [("Valentía ante la propia oscuridad", "Se conoce lo peor y no aparta la vista."),
  ("Perspicaz", "Huele las intenciones ocultas antes del saludo."),
  ("Superviviente adaptable", "Cae de pie hasta cuando lo empujan.")],
 [("Obsesivo", "Cuando algo se le clava, escarba hasta sangrar."),
  ("Inestable", "Su tempestad interior tiene fugas."),
  ("Desconfía del bien", "La amabilidad gratuita le parece una trampa cara.")],
 [("Romper las cadenas de nacimiento", "Lo que me impusieron al nacer no es mi techo."),
  ("Saldar cuentas con quien apagó la luz", "Alguien dejó a oscuras mi barrio. Sé quién."),
  ("Ser la luz que no tuve", "Un farol encendido para el próximo crío del callejón.")],
 [("Volver a la jaula", "Cualquier jaula. Con cualquier nombre amable."),
  ("Su propia tormenta", "Perder el control justo con quien no debía."),
  ("Que le crean incapaz de bien", "Y peor: que tengan razón.")],
 [("La libertad está por encima de todo", "Vale más un día en el borde que una vida en la fila."),
  ("Las etiquetas se arrancan", "Nadie es el nombre que le pusieron otros."),
  ("La luz se demuestra a oscuras", "Cualquiera es bueno a mediodía.")],
 [("El farol de la esquina", "Bajo esa luz roja me salvaron una vez. Y otra."),
  ("Mi nombre elegido", "Me lo gané. El otro lo llevo de recuerdo, no de dueño."),
  ("La banda de los tejados", "Los que corrían conmigo cuando abajo era peligroso.")]),

("mes_de_les_estrelles", "Mes de las Estrellas", "Energía Suprema",
 "El Guardián de los Hilos del Destino", "Nacido bajo la noche de las tres lunas: lleva el eco del universo y la responsabilidad de comprenderlo.",
 "Los nacidos bajo la conjunción: sagaces, compasivos a escala de mundo, viejos desde la cuna.",
 {"origin": "Observatorios, faros del interior y aldeas que guardan la Noche de las Tres Lunas.",
  "culture": "Mirar el cielo es un oficio; anotarlo, un deber; interpretarlo, un riesgo asumido.",
  "environment": "Cúpulas con grietas de tanto abrirse, mapas celestes, escaleras de caracol.",
  "importantEvents": ["La Noche de las Tres Lunas, que solo ocurre cada generación",
                       "El Error del Cometa, cuando una mala lectura movió una guerra"],
  "deities": ["la_tejedora_de_estrellas", "el_oraculo_fragmentado"],
  "symbols": ["Las tres lunas alineadas", "El hilo rojo anudado", "El astrolabio heredado"],
  "traditions": ["Anotar la posición de las estrellas en cada nacimiento del pueblo",
                  "Deshacer un nudo el día del error propio, en público"]},
 [("Mira el cuadro completo", "Antes de opinar del árbol, pregunta por el bosque."),
  ("Ternura telescópica", "Quiere a la gente mejor desde cierta distancia. Trabaja en ello."),
  ("Preciso como un tránsito", "Llega, dice y actúa con puntualidad astronómica.")],
 [("Sagacidad profética", "Junta puntos que nadie más ve como constelación."),
  ("Compasión universal", "Le importan también los desconocidos de los mapas."),
  ("Visión clara del tiempo", "Pasado, presente y futuro le caben en la misma frase.")],
 [("Expectativas imposibles", "Se exige órbitas perfectas en un mundo que tambalea."),
  ("Aislamiento intelectual", "Desde tan arriba, cuesta oír las voces de la calle."),
  ("Frialdad aparente", "Calcula tanto el gesto justo que llega tarde al abrazo.")],
 [("Escribir la profecía que altere la historia", "Una lectura correcta a tiempo. Solo pido eso."),
  ("Corregir el Error del Cometa", "Aquella guerra empezó por una coma celeste. Se puede cerrar."),
  ("Ver la próxima Noche de las Tres Lunas", "Y estar a la altura de lo que traiga.")],
 [("Que no haya patrón", "Que el cielo sea hermoso y mudo."),
  ("Leer mal el hilo", "Un nudo equivocado en el destino de otro."),
  ("La noche nublada decisiva", "Que el cielo se esconda justo cuando más se le necesita.")],
 [("El saber debe compartirse", "Un cielo leído en secreto no ilumina a nadie."),
  ("Cada vida es una estrella", "Ninguna es menor: solo está más lejos."),
  ("El destino se teje, no se sufre", "Los hilos están dados; el nudo lo eliges tú.")],
 [("El astrolabio heredado", "Cuatro generaciones mirando arriba con estas mismas manos."),
  ("Mi aldea de nacimiento", "Todos saben qué cielo hacía la noche en que nací. Todos."),
  ("El cuaderno de nacimientos", "Cada vecino tiene su página estelar. La mía tiene tres lunas.")]),
]


def main() -> None:
    escritos = 0
    for (mid, nombre, energia, alin_titulo, alin_desc, descripcion, lore,
         pers, virt, flaw, goal, fear, ideal, bond) in MESES:
        pool = ENERGIA[energia]
        prefijo = mid.replace("mes_", "")
        carta = {
            "id": mid,
            "name": nombre,
            "type": "BACKGROUND",
            "tier": 1,
            "description": descripcion,
            "lore": {
                "origin": lore["origin"],
                "culture": lore["culture"],
                "environment": lore["environment"],
                "importantEvents": lore["importantEvents"],
                "deities": lore["deities"],
                "symbols": lore["symbols"],
                "traditions": lore["traditions"],
            },
            "characterCreation": {
                "choosePersonality": 1,
                "personalities": ops(prefijo, "personality", pers + pool["personalities"]),
                "chooseVirtue": 1,
                "virtues": ops(prefijo, "virtue", virt + pool["virtues"]),
                "chooseFlaw": 1,
                "flaws": ops(prefijo, "flaw", flaw + pool["flaws"]),
                "chooseGoal": 1,
                "goals": ops(prefijo, "goal", goal + pool["goals"]),
                "chooseFear": 1,
                "fears": ops(prefijo, "fear", fear + pool["fears"]),
                "chooseIdeal": 1,
                "ideals": ops(prefijo, "ideal", ideal + pool["ideals"]),
                "chooseBond": 1,
                "bonds": ops(prefijo, "bond", bond + pool["bonds"]),
            },
            "alignment": {"title": alin_titulo, "description": alin_desc},
            "tags": ["MES_DE_NACIMIENTO", energia.upper().replace(" ", "_"), alin_titulo.upper().replace(" ", "_")],
        }
        destino = OUT / f"{mid}.json"
        destino.write_text(json.dumps(carta, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        escritos += 1
    print(f"Trasfondos migrados al esquema characterCreation: {escritos}/12")


if __name__ == "__main__":
    main()
